// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCartDataLayer.Context;

namespace ShoppingCartDataLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("ShoppingCartDataLayer.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("HasBeenApplied");

                    b.Property<bool?>("HasBeenUsed");

                    b.Property<int?>("Percentage");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new { Id = 1, HasBeenApplied = false, Percentage = 10 }
                    );
                });

            modelBuilder.Entity("ShoppingCartDataLayer.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("DiscountId");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("Items");

                    b.HasData(
                        new { Id = 1, Description = "Have a break, have a kit kat", Name = "Kit Kats", Price = 1.10m }
                    );
                });

            modelBuilder.Entity("ShoppingCartDataLayer.Models.Order", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ItemId");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShoppingCartDataLayer.Models.Item", b =>
                {
                    b.HasOne("ShoppingCartDataLayer.Models.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountId");
                });
#pragma warning restore 612, 618
        }
    }
}
